data_file: file.csv
stopwords: stopwords.txt
number_of_topic_top_words: 10
output_dir: models/

tuner:
  trials: 5
  study:
    study_name: test
    storage: sqlite_url
    seed: 888
    direction: minimize
    resume: true
  optimize:
    n_jobs: 1

vectorizer_hparams:
  max_df:
    - 0.7
    - 1.0

lda_hparams:
  alpha:
    - 10.0e-5
    - 1.0
  beta:
    - 10.0e-5
    - 1.0
  num_topics:
    - 3
    - 100
  iterations:
    - 10
    - 500
  decay:
    - 0.5
    - 1.0
  offset:
    - 10.0
    - 100.0
